// Generated by CoffeeScript 1.8.0
(function() {
  var cheerio, escaper, exec, file, fs, joinTotal, last, parse, util;

  util = require('util');

  fs = require('fs');

  cheerio = require('cheerio');

  escaper = require('true-html-escape');

  exec = (require('child_process')).exec;

  file = 'test';

  last = exec("pdftohtml -p -noframes -i " + file + ".pdf", function(error, stdout, stderr) {});

  last.stdout.on('data', function(data) {
    return fs.readFile("" + file + ".html", function(err, html) {
      var $, arr, i, line, _i, _len;
      $ = cheerio.load(html.toString());
      html = (escaper.unescape($('body').html())).replace(/<br>/g, '').replace(/<b>/g, '').replace(/<\/b>/g, '');
      arr = html.split('\n');
      data = {};
      data['Total Less Charge'] = 0;
      for (i = _i = 0, _len = arr.length; _i < _len; i = ++_i) {
        line = arr[i];
        parse(arr, i, data);
      }
      return console.log(data);
    });
  });

  parse = function(arr, i, data) {
    var line;
    line = arr[i];
    if (line[0] === '$' && line[line.length - 1] === '*') {
      data['Total Less Charge'] += Number(line.slice(1, -1));
    }
    switch (line) {
      case 'Date Received:':
        return data['Date Received'] = arr[i + 1];
      case 'Account # :':
        return data['Account #'] = arr[i + 1];
      case 'Lot # :':
        return data['Lot #'] = arr[i + 1];
      case 'Settlement # :':
        return data['Settlement #'] = arr[i + 1];
      case 'Net Weight Received:':
        return data['Net Weight Received'] = arr[i + 1] + ' ' + arr[i + 2];
      case 'After Processing Weight:':
        return data['After Processing Weight'] = arr[i + 1];
      case 'Gold Total:':
        return data['Gold Total'] = joinTotal(arr, i + 1);
      case 'Silver Total:':
        return data['Silver Total'] = joinTotal(arr, i + 1);
      case 'Platinum Total:':
        return data['Platinum Total'] = joinTotal(arr, i + 1);
      case 'Palladium Total':
        return data['Palladium Total'] = joinTotal(arr, i + 1);
    }
  };

  joinTotal = function(arr, i) {
    var total;
    return total = arr[i].slice(0, -2) + arr[i + 1] + '%';
  };

}).call(this);
